### ISSUE TITLE
Lint error: ruff doesn't support pyupgrade anymore

### ISSUE THREAD

**Issue by amitfin** [ludeeus/integration_blueprint#111]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Github lint step always fails:
```
Run python3 -m ruff check .
error: Failed to parse `/home/runner/work/retry/retry/.ruff.toml`: TOML parse error at line 44, column 2
   |
44 | [pyupgrade]
   |  ^^^^^^^^^
unknown field `pyupgrade`, expected one of `allowed-confusables`, `builtins`, `cache-dir`, `dummy-variable-rgx`, `exclude`, `extend`, `extend-exclude`, `extend-include`, `extend-ignore`, `extend-select`, `extend-fixable`, `extend-unfixable`, `external`, `fix`, `fix-only`, `fixable`, `format`, `force-exclude`, `ignore`, `ignore-init-module-imports`, `include`, `line-length`, `tab-size`, `required-version`, `respect-gitignore`, `select`, `show-source`, `show-fixes`, `src`, `namespace-packages`, `target-version`, `task-tags`, `typing-modules`, `unfixable`, `flake8-annotations`, `flake8-bandit`, `flake8-bugbear`, `flake8-builtins`, `flake8-comprehensions`, `flake8-errmsg`, `flake8-quotes`, `flake8-self`, `flake8-tidy-imports`, `flake8-type-checking`, `flake8-gettext`, `flake8-implicit-str-concat`, `flake8-import-conventions`, `flake8-pytest-style`, `flake8-unused-arguments`, `isort`, `mccabe`, `pep8-naming`, `pycodestyle`, `pydocstyle`, `pylint`, `per-file-ignores`, `extend-per-file-ignores`

Error: Process completed with exit code 2.
```

The root cause is [this PR](https://github.com/SchemaStore/schemastore/pull/2974), which removed `pyupgrade` from ruff.

### Reproduction steps

Link to Github job example: [here](https://github.com/amitfin/retry/actions/runs/5113202676/jobs/9192140386).

### Debug logs

```text
N/A
```

### Diagnostics dump

N/A

**Comment by ludeeus** [comment]
ruff is not updated in this repo..
see #110

**Comment by amitfin** [comment]
(Sharing my investigation information just in case it helps, but keeping the bug closed)
@ludeeus , the problem seems to be in [.ruff.toml](https://github.com/ludeeus/integration_blueprint/blob/main/.ruff.toml) and is not related to the library version. [This PR](https://github.com/SchemaStore/schemastore/pull/2974) changed the schema of the file, and [[pyupgrade] section](https://github.com/ludeeus/integration_blueprint/blob/20e3852994e7d4dd856bba8cb382fb6e602b934a/.ruff.toml#L44) is not allowed anymore.
