### ISSUE TITLE
Exclude markdown from removing trailing whitespace

### ISSUE THREAD

**Issue by ptr727** [ludeeus/integration_blueprint#115]
### System Health details

NA

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Template settings removes trailing whitespace on save, this breaks markdown formatting.

Suggest add exclusion for markdown:

```json
"[markdown]": {
    "files.trimTrailingWhitespace": false
}
```

### Reproduction steps

1. Use `trailing double space for newline  ` in .md file
2. Save
3. .md formattign gets broken as traling spaces for newline is removed.

### Debug logs

```text
NA
```

### Diagnostics dump

NA

**Comment by ludeeus** [comment]
Please open a PR, if you would like that to change.
