### ISSUE TITLE
Python 3.10 will be depreciated

### ISSUE THREAD

**Issue by antonverburg** [ludeeus/integration_blueprint#134]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Homeassistant won't work from version 2023.8 with python 3.10. Can we update the devcontainer.json to an image that contains python 3.11?

### Describe the solution you'd like

Update "image": "mcr.microsoft.com/vscode/devcontainers/python:0-3.10-bullseye" in devcontainer.json to an image that contains python 3.11 (unfortunately there is not an mcr.microsoft.com/vscode/devcontainers/python container as far as I see).

### Describe alternatives you've considered

-

### Additional context

-

**Comment by ludeeus** [comment]
Sure, do a PR for it and i can look.
