### ISSUE TITLE
FR: Add options flow

### ISSUE THREAD

**Issue by bj00rn** [ludeeus/integration_blueprint#199]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

There is no options flow :-)

### Describe the solution you'd like

Add scaffold implementation of options flow https://developers.home-assistant.io/docs/config_entries_options_flow_handler/ to template

### Describe alternatives you've considered

n/a

### Additional context

I think a template for options flow would be a nice addition

**Comment by ludeeus** [comment]
https://github.com/home-assistant/example-custom-config/tree/master/custom_components would be a better place to add it
