### ISSUE TITLE
Auto Apply FR Labels (enhancement) to this Issue Template.

### ISSUE THREAD

**Issue by njobrien1006** [ludeeus/integration_blueprint#219]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm always frustrated manually applying FR labels.

### Describe the solution you'd like

Labels automatically applying to this FR form.

### Describe alternatives you've considered

Manually applying them. However, manual == prone to error.

### Additional context

It appears that this form already has the label assigned to it. However, it does not populate it. I suspect the `+` is an unsupported char?   I fixed where [I use this from](https://github.com/njobrien1006/hass_traeger/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.yml) to use `enhancement` but figured I should report upstream.

**Comment by ludeeus** [comment]
This is not upstream, this is an example.

**Comment by njobrien1006** [comment]
Understood. It is a fantastic example.

Just pointing out that [labels](https://github.com/ludeeus/integration_blueprint/blob/c4963a13df8cbdd6852741da8f615d11c277f9b1/.github/ISSUE_TEMPLATE/feature_request.yml?plain=1#L4) is not working as intended.
