### ISSUE TITLE
Adding instruction on how to install with HACS 

### ISSUE THREAD

**Issue by oncleben31** [ludeeus/integration_blueprint#35]
**Is your feature request related to a problem? Please describe.**
Not really. Just to make it clearer on the installation options for the not experienced users who could find the custom component repository not thru HACS.

**Describe the solution you'd like**
Add different installation options in the documentation:
-  Manually
- Thru HACS (with default repo)
- Thru HACS with adding the repository manually.

**Describe alternatives you've considered**
Doing nothing ;-)

**Additional context**
If you agree on the idea. I can work on a PR.

**Comment by ludeeus** [comment]
I don't understand, this repo should never be "installed" with HACS, it's purpose is to help developers get started with their custom_integration.

**Comment by oncleben31** [comment]
I'm thinking in the part after: `README content if this was a published component:`
To propose a template of basic documentation explaining how to install the custom component. As your template is HACS ready, basic instruction on how to install in HACS could avoid any developper to write again the instructions.

**Comment by ludeeus** [comment]
sure :+1:

**Comment by oncleben31** [comment]
OK let's do another PR ;-)
