### ISSUE TITLE
Add tag on the template to be able to reference a specific version.

### ISSUE THREAD

**Issue by oncleben31** [ludeeus/integration_blueprint#46]
**Is your feature request related to a problem? Please describe.**
In [cookiecutter-home-assistant-custom-component](https://github.com/oncleben31/cookiecutter-homeassistant-custom-component) I try to keep synchronized with the blueprint template. I plan to release once a month. It could be easier for users to know what version of the blueprint the cookiecutter will generate.

**Describe the solution you'd like**
The blueprint maintainers could add a tag or a release after major modifications.

**Describe alternatives you've considered**
open for other suggestions

**Additional context**
N/A

**Comment by Limych** [comment]
@oncleben31, as an option you can use my modification of this repository in which where are separate branch with blueprint which you can securely merge with you project at any time: https://github.com/Limych/ha-blueprint
