### ISSUE TITLE
Test requirements unmet due to outdated version of pip

### ISSUE THREAD

**Issue by dummylabs** [ludeeus/integration_blueprint#70]
## Version of the custom_component
0.0.1

## Describe the bug
1. Open repo in the devcontainer
2. Set up venv, install test requirements with pip. It will complain about the dependencies:
```
(venv) container# pip check
pytest-homeassistant-custom-component 0.4.0 has requirement sqlalchemy==1.4.13, but you have sqlalchemy 1.4.31.
homeassistant 2021.6.0b0 has requirement attrs==21.2.0, but you have attrs 21.4.0.
homeassistant 2021.6.0b0 has requirement httpx==0.18.0, but you have httpx 0.22.0.
homeassistant 2021.6.0b0 has requirement requests==2.25.1, but you have requests 2.27.1.
```

3. `pytest tests\` command works fine with  default tests from integration_blueprint, but causes the error with an inherited repo containing a custom component: 
```
aiohttp 3.8.1 requires async-timeout<5.0,>=4.0.0a3
```

## Solution
1. Upgrade pip to the latest version (pip-22.0.3)
2. Run `pip3 install -r requirements_test.txt` again

**Comment by ludeeus** [comment]
`pip3 install -r requirements_test.txt --use-deprecated=legacy-resolver`

**Comment by ludeeus** [comment]
Tests was removed in <https://github.com/ludeeus/integration_blueprint/commit/15feac505d7b21e6c17e48f918fa04cf0e340a0e> ref <https://github.com/ludeeus/integration_blueprint/issues/83> so this is no longer needed 👍
