### ISSUE TITLE
Remove deprecated CONNECTION_CLASS attribute in flow handler?

### ISSUE THREAD

**Issue by bj00rn** [ludeeus/integration_blueprint#84]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

CONNECTION_CLASS is deprecated since since 2021.6.0

https://github.com/ludeeus/integration_blueprint/blob/1c5dcfdfb6472122c484ad5738d38d19550b94f3/custom_components/integration_blueprint/config_flow.py#L23

Kudos for a great template!

### Describe the solution you'd like

Remove CONNECTION_CLASS

### Describe alternatives you've considered

Keep it for backwards compatibility past 2021.6.0

### Additional context

N/A

**Comment by ludeeus** [comment]
Removed in <https://github.com/ludeeus/integration_blueprint/commit/b7a34be397bbb65b8b85c74e839dd0bf35b6b915> 👍 

Backward compatibility is not a concern for this repository.
