### ISSUE TITLE
Suggestion: Use subdir for hass data

### ISSUE THREAD

**Issue by bj00rn** [ludeeus/integration_blueprint#85]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Currently hass intallation data clogs up directory when the devcontainer is spun up

### Describe the solution you'd like

1. create a subdir `hass` or the likes
2. symlink `custom_components`, `configuration.yaml` into this dir.
3. in scripts/develop -> `cd ../hass` and do install there
4. .gitignore could then be `hass` too making it immune to additional hass artifacts, backups etc

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by ludeeus** [comment]
What you describe is how it used to be, that was confusing for people.
The way it was now is simpler, but you control your repository so you can do whatever you need/want there ;)

**Comment by bj00rn** [comment]
> What you describe is how it used to be, that was confusing for people. The way it was now is simpler, but you control your repository so you can do whatever you need/want there ;)

ah I see. Thanks!

**Comment by ludeeus** [comment]
FWIW <https://github.com/ludeeus/integration_blueprint/pull/102>
