### ISSUE TITLE
Suggestion: Provide ssh pubkey to devcontainer

### ISSUE THREAD

**Issue by bj00rn** [ludeeus/integration_blueprint#86]
### Checklist

edit: found https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials, maybe it's just my credentials helper thats buggering me

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I can't push code to my project from devcontainer

### Describe the solution you'd like

Push to my repository from devcontainer

Mount in ssh pub key in devcontainer might be an option? Maybe commented out until explicitly enabled

### Describe alternatives you've considered

pushing from another terminal

### Additional context

N/A

**Comment by ludeeus** [comment]
Clone the repo with SSH and not https and it works.
Nothing that can/should be changed here.

**Comment by bj00rn** [comment]
> Clone the repo with SSH and not https and it works. Nothing that can/should be changed here.

I think it's my credentials helper that was causing problems
