### ISSUE TITLE
Don't run hass (devcontainer) in workspace folder

### ISSUE THREAD

**Issue by golles** [ludeeus/integration_blueprint#87]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Before I start, thank you again for improving this repo. As a none python developer, your blueprint greatly helped me by extending my Home Assistant with extra functionality!

I also like that you use a standard container for the dev container!

I'm not so happy with the fact that Home Assistant runs inside the workspace folder, making it "dirty" with Home Assistant files that are unrelated to the project (custom_component).
I see you fix this by the `.gitignore` file, in my opinion, this is masking the problem, not actually fixing it.

### Describe the solution you'd like

My solution would be to adjust the `develop` script to something like this:

```bash
#!/usr/bin/env bash

set -e

# Create a clean working directory for Home Assistant
sudo rm -rf /hass
sudo mkdir /hass
sudo chown vscode:vscode /hass

# Copy config and custom_components
cp .devcontainer/configuration.yaml /hass
cp -r custom_components/ /hass

# Start Home Assistant
hass -c /hass --debug
```

### Describe alternatives you've considered

Not really alternatives, but I do see some things are not perfect:
- The use of `sudo`/`chown`, IMO not an issue, `/home/vscode/hass` could be used instead (user home dir)
- My `configuration.yaml` is still in the `.devcontainer`, I think this is the best place to put this file, as this is solely for the dev container.

(I also still have the `devcontainer.json` inside the `.devcontainer` folder, as my VSC doesn't popup a dialog to open in a container if the `devcontainer.json` inside the root).

### Additional context

N/A

**Comment by ludeeus** [comment]
It used to be like that, you are free to change your own repo to your liking, this repo will not go back to that.

**Comment by ludeeus** [comment]
FWIW <https://github.com/ludeeus/integration_blueprint/pull/102>
